[package]
name = "blks-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license = "LGPL-3.0-or-later"
description = "High-Performance 384-Bit Cryptographic Tree-Hash Engine (LGPLv3)"

[lib]
name = "blks_core"
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
rayon = "1.10"
memmap2 = "0.9"

[dev-dependencies]
